[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator = "AVRiBJuuLqtLojDtEAy6XPe4NuxSnzZjNZN9GghzMKNg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kasuba97/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
